name: spell
on: [push, pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: misspell
        uses: reviewdog/action-misspell@v1.2.0
        with:
          github_token: ${{ secrets.github_token }}
          locale: "UK"
