name: misspell
on: [push, pull_request]
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using misspell
        uses: moneyforward/misspell-action@v0
