name: tests


on: [push, pull_request]

jobs:
  linux_gcc:
    name: ${{ matrix.config }} Linux ${{ matrix.arch }}-bit (GCC)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [32, 64]
        include:
          - arch: 32
            COMPILE_ARCH: i386
            make_ARCH: x86
          - arch: 64
            COMPILE_ARCH: amd64
            make_ARCH: x86_64
#          - c: gcc

    steps:
    - name: Install tools
      run: |
        if [ ${{ matrix.arch }} -eq 32 ]; then
            sudo dpkg --add-architecture i386
            sudo apt-get update -y
        fi
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        cd build/linux
        if [ ${{ matrix.arch }} -eq 32 ]; then
          make -j 4 ARCH=${{ matrix.make_ARCH }} COMPILE_ARCH=${{ matrix.COMPILE_ARCH }}
        fi
        if [ ${{ matrix.arch }} -eq 64 ]; then
          make -j 4 ARCH=${{ matrix.make_ARCH }} COMPILE_ARCH=${{ matrix.COMPILE_ARCH }}
        fi
    - uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: build/linux/build
        if-no-files-found: error
#        retention-days: 5
